
#ifndef cheddar_generated_rustyh_h
#define cheddar_generated_rustyh_h

/**
 * This file was automatically generated by rusty-cheddar.
 * It would probably be wise not to mess with it.
 */


#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>




void call_setter_with_random(void (*setter)(uint32_t , void const* ), void const* context);



#ifdef __cplusplus
}
#endif


#endif
